databases:
  - name: project_conversation
    databaseName: project_conversation_development
    user: postgres
    plan: free

services:
  - type: web
    plan: free
    name: project_conversation
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project_conversation
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
